// <auto-generated />
using System;
using EKZKPZ.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EKZKPZ.Migrations
{
    [DbContext(typeof(ClothingContext))]
    [Migration("20221216102045_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EKZKPZ.Models.Clothing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("DATEDIFF(MONTH, [ProductionDate], GETDATE()) * 10");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clothing");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            Discount = 0,
                            Model = "12afe321",
                            Name = "Sweetshot",
                            Price = 100f,
                            ProductionDate = new DateTime(2022, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 5,
                            Size = 2
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Adiddas",
                            Discount = 0,
                            Model = "12asdfdf1",
                            Name = "Shoes",
                            Price = 500f,
                            ProductionDate = new DateTime(2022, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 10,
                            Size = 0
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Puma",
                            Discount = 0,
                            Model = "12adfer321",
                            Name = "Cap",
                            Price = 50f,
                            ProductionDate = new DateTime(2022, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 3,
                            Size = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
